import type { LiturgicalColor } from "@om/contracts";

import { LITURGICAL_COLORS } from "@om/contracts";

import type { ArtifactModel, NormalizedToken, TokenManifest } from "./model.js";

import {
  cssValueForToken,
  generatedArtifactPaths,
  MANIFEST_FORMAT_VERSION,
  stableJson,
  tokenPathToCssCustomProperty
} from "./model.js";
import { assertLiturgicalOverrideAllowed } from "../resolve-tokens.js";

const layerDeclaration = "@layer om.defaults, om.app, om.brand, om.liturgical, om.accessibility;";

export type EmittedArtifacts = Readonly<Record<(typeof generatedArtifactPaths)[number], string>>;

export function emitArtifacts(model: ArtifactModel): EmittedArtifacts {
  const manifestJson = stableJson(model.manifest);
  const metadataJson = stableJson(model.metadata);
  const primitivesCss = emitPrimitivesCss(model.primitiveTokens);
  const lightCss = emitSchemeCss("light", model.lightTokens);
  const darkCss = emitSchemeCss("dark", model.darkTokens);
  const liturgicalCss = emitLiturgicalCss(model.liturgicalTokens);
  const accessibilityCss = emitAccessibilityCss(model.accessibilityTokens);
  const combinedCss = [
    layerDeclaration,
    "",
    withoutLayerDeclaration(primitivesCss),
    withoutLayerDeclaration(lightCss),
    withoutLayerDeclaration(darkCss),
    withoutLayerDeclaration(liturgicalCss),
    withoutLayerDeclaration(accessibilityCss)
  ].join("\n");

  return {
    "index.js": emitIndexJs(),
    "index.d.ts": emitIndexDts(),
    "tokens.js": emitTokensJs(model.manifest),
    "tokens.d.ts": emitTokensDts(),
    "manifest.json": manifestJson,
    "metadata.json": metadataJson,
    "css/om-tokens.css": normalizeCss(combinedCss),
    "css/om-primitives.css": primitivesCss,
    "css/om-tokens.light.css": lightCss,
    "css/om-tokens.dark.css": darkCss,
    "css/om-liturgical.css": liturgicalCss,
    "css/om-accessibility.css": accessibilityCss
  };
}

export function emitPrimitivesCss(tokens: readonly NormalizedToken[]): string {
  return normalizeCss(`${layerDeclaration}

@layer om.defaults {
  :root {
${emitDeclarations(tokens)}
  }
}`);
}

export function emitSchemeCss(
  scheme: "light" | "dark",
  tokens: readonly NormalizedToken[]
): string {
  return normalizeCss(`${layerDeclaration}

@layer om.defaults {
  [data-om-theme="${scheme}"] {
${emitDeclarations(tokens)}
  }
}`);
}

export function emitLiturgicalCss(tokens: readonly NormalizedToken[]): string {
  const liturgicalVariables = new Map<LiturgicalColor, NormalizedToken[]>();
  for (const color of LITURGICAL_COLORS) {
    liturgicalVariables.set(color, []);
  }

  for (const token of tokens) {
    assertLiturgicalOverrideAllowed(token.path);
    const color = LITURGICAL_COLORS.find((candidate) =>
      token.path.startsWith(`liturgical.${candidate}.`)
    );
    if (color === undefined) {
      liturgicalVariables.get("red")?.push(token);
    } else {
      liturgicalVariables.get(color)?.push(token);
    }
  }

  return normalizeCss(`${layerDeclaration}

@layer om.liturgical {
${LITURGICAL_COLORS.map((color) => emitSelector(`[data-om-liturgical-color="${color}"]`, liturgicalVariables.get(color) ?? [])).join("\n\n")}
}`);
}

export function emitAccessibilityCss(tokens: readonly NormalizedToken[]): string {
  const focusTokens = tokens.filter((token) => token.path.includes(".focus."));
  const motionTokens = tokens.filter((token) => token.path.includes(".motion."));
  const textTokens = tokens.filter((token) => token.path.includes(".text."));

  return normalizeCss(`${layerDeclaration}

@layer om.accessibility {
${emitSelector('[data-om-contrast="high"]', [])}

${emitSelector('[data-om-contrast="forced"]', [])}

${emitSelector('[data-om-motion="reduced"]', motionTokens)}

${emitSelector('[data-om-text-scale="large"]', textTokens)}

${emitSelector('[data-om-text-scale="larger"]', textTokens)}

${emitSelector('[data-om-focus-visibility="enhanced"]', focusTokens)}

${emitSelector('[data-om-color-independence="true"]', [])}

  @media (prefers-reduced-motion: reduce) {
${indentSelector(":root", motionTokens, 4)}
  }

  @media (prefers-contrast: more) {
${indentSelector(":root", [], 4)}
  }

  @media (forced-colors: active) {
${indentSelector(":root", focusTokens, 4)}
  }
}`);
}

function emitIndexJs(): string {
  return `export * from "./tokens.js";\n`;
}

function emitIndexDts(): string {
  return `export * from "./tokens.js";\n`;
}

function emitTokensJs(manifest: TokenManifest): string {
  const tokenDefinitions = stableJson(manifest.tokens).trim();
  const tokenPaths = stableJson(manifest.tokenPaths).trim();
  const supportedColorSchemes = stableJson(manifest.supportedColorSchemes).trim();
  const supportedLiturgicalColors = stableJson(manifest.supportedLiturgicalColors).trim();

  return `// Generated by @om/tokens Phase 1B. Experimental while packages remain private.
export const manifestFormatVersion = ${String(MANIFEST_FORMAT_VERSION)};
export const normalizedTokenDefinitions = Object.freeze(${tokenDefinitions}.map((token) => Object.freeze(token)));
export const tokenPaths = Object.freeze(${tokenPaths});
export const supportedColorSchemes = Object.freeze(${supportedColorSchemes});
export const supportedLiturgicalColors = Object.freeze(${supportedLiturgicalColors});

export function tokenPathToCssCustomProperty(path) {
  return \`--om-\${path
    .split(".")
    .map((segment) =>
      segment
        .replace(/([a-z0-9])([A-Z])/gu, "$1-$2")
        .replace(/_/gu, "-")
        .toLowerCase()
    )
    .join("-")}\`;
}

export function hasTokenPath(path) {
  return tokenPaths.includes(path);
}

export function getTokenMetadata(path) {
  return normalizedTokenDefinitions.find((token) => token.path === path);
}
`;
}

function emitTokensDts(): string {
  return `// Generated by @om/tokens Phase 1B. Experimental while packages remain private.
import type { ColorScheme, LiturgicalColor, TokenCategory, TokenPath, TokenStability, TokenValue, TokenValueType } from "@om/contracts";

export declare const manifestFormatVersion: 1;

export type NormalizedTokenDefinition = {
  readonly path: TokenPath;
  readonly category: TokenCategory;
  readonly type: TokenValueType;
  readonly value: TokenValue;
  readonly resolvedValue: string | number;
  readonly description: string;
  readonly stability: TokenStability;
  readonly deprecated: boolean;
  readonly replacement?: TokenPath;
  readonly layer: TokenCategory;
  readonly colorScheme?: ColorScheme;
};

export declare const normalizedTokenDefinitions: readonly NormalizedTokenDefinition[];
export declare const tokenPaths: readonly TokenPath[];
export declare const supportedColorSchemes: readonly ColorScheme[];
export declare const supportedLiturgicalColors: readonly LiturgicalColor[];

export declare function tokenPathToCssCustomProperty(path: TokenPath): string;
export declare function hasTokenPath(path: TokenPath): boolean;
export declare function getTokenMetadata(path: TokenPath): NormalizedTokenDefinition | undefined;
`;
}

function emitDeclarations(tokens: readonly NormalizedToken[]): string {
  return tokens
    .map(
      (token) =>
        `    ${tokenPathToCssCustomProperty(token.path)}: ${cssValueForToken(token.value)};`
    )
    .join("\n");
}

function emitSelector(selector: string, tokens: readonly NormalizedToken[]): string {
  return indentSelector(selector, tokens, 2);
}

function indentSelector(
  selector: string,
  tokens: readonly NormalizedToken[],
  spaces: number
): string {
  const indentation = " ".repeat(spaces);
  const childIndentation = " ".repeat(spaces + 2);
  if (tokens.length === 0) {
    return `${indentation}${selector} {
${childIndentation}/* Reserved for approved Phase 1B token output. */
${indentation}}`;
  }

  return `${indentation}${selector} {
${tokens.map((token) => `${childIndentation}${tokenPathToCssCustomProperty(token.path)}: ${cssValueForToken(token.value)};`).join("\n")}
${indentation}}`;
}

function withoutLayerDeclaration(css: string): string {
  return css.replace(`${layerDeclaration}\n\n`, "");
}

function normalizeCss(css: string): string {
  return `${css.trim()}\n`;
}
